name: Build and Deploy - GaraViet Policy Website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: quangdao9a2
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: quangdao9a2/garageviet-policy:latest
          no-cache: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-22.04
    needs: build-and-push-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_PROD }}
          username: ${{ vars.HOST_USERNAME }}
          password: ${{ secrets.PASS_WORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd gara-viet
            echo "🔄 Force pulling latest policy website image..."
            docker pull quangdao9a2/garageviet-policy:latest --quiet
            echo "🛑 Stopping current policy website containers..."
            docker-compose -f docker-compose.policy.yml down
            echo "🚀 Starting new policy website containers..."
            docker-compose -f docker-compose.policy.yml up -d
            echo "🧹 Cleaning up old images and containers..."
            docker image prune -af
            docker container prune -f
            docker volume prune -f
            echo "✅ Policy website deployment completed!"
